package org.perfcake.idea.editor.colors;

/**
 * Created by miron on 2.11.2014.
 */
public enum ColorType {
    SCENARIO_FOREGROUND,
    SCENARIO_BACKGROUND,
    PROPERTIES_FOREGROUND,
    PROPERTIES_BACKGROUND,
    PROPERTY_FOREGROUND,
    PROPERTY_BACKGROUND,
    GENERATOR_FOREGROUND,
    GENERATOR_BACKGROUND,
    SENDER_FOREGROUND,
    SENDER_BACKGROUND,
    REPORTING_FOREGROUND,
    REPORTING_BACKGROUND,
    REPORTER_FOREGROUND,
    REPORTER_BACKGROUND,
    DESTINATION_FOREGROUND,
    DESTINATION_BACKGROUND,
    MESSAGES_FOREGROUND,
    MESSAGES_BACKGROUND,
    MESSAGE_FOREGROUND,
    MESSAGE_BACKGROUND,
    VALIDATION_FOREGROUND,
    VALIDATION_BACKGROUND,
    VALIDATOR_FOREGROUND,
    VALIDATOR_BACKGROUND;
}
